version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8080:80"
    env_file: MYSQL_credentials.txt
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    depends_on:
      - db
    networks:
      - wp_network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    env_file: MYSQL_credentials.txt
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - ./db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    networks:
      - wp_network

volumes:
  db_data: {}
  wordpress: {}

networks:
  wp_network:
    driver: bridge
